name = "shortify"
compatibility_date = "2025-09-03"

type = "javascript"

[site]
bucket = "./dist"         
entry-point = "./workers"

[[routers]]
name = "api"
rules = [
  { pattern = "/api/*", type = "include" }
]

[observability]
enabled = true
